numpy:
  - 1.23
  - 1.23
  - 1.26

fabio:
  - 2024.9.0
  - 2024.4.0
  - 2023.10.0
  
python:
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  
zip_keys:
  - python
  - numpy
  - fabio
