{% set version = "0.8.5" %}

package:
  name: azint
  version: {{ version }}

source:
  path: ..

build:
  number: 3
  script: pip install .
requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - numpy
    - pybind11
    
  run:
    - python
    - numpy
    
test:
  source_files:
    - tests/*.py
    - tests/test.poni
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  license: MIT
  license_file: ../LICENSE

 
