package:
  name: azint
  version: "{{ SETUPTOOLS_SCM_PRETEND_VERSION }}"

source:
  path: ..

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - numpy
    - fabio
    - pybind11
    - setuptools_scm
    
  run:
    - python
    - numpy
    - fabio
    
test:
  source_files:
    - tests/*.py
    - tests/test.poni
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  license: MIT
  license_file: ../LICENSE

 
